app_bokeh/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from app_bokeh import views as bokeh_views
from django.conf import settings

urlpatterns = [
    url(r'^json/$',bokeh_views.bokeh_json),
    url(r'^id/(?P<bokeh_id>\d+)/image/$',bokeh_views.bokeh_image),
    url(r'^id/(?P<bokeh_id>\d+)/data/$',bokeh_views.data),

    url(r'^$',bokeh_views.bokeh_index),
    url(r'^form/$',bokeh_views.bokeh_form),
    url(r'^id/(?P<bokeh_id>\d+)/$', bokeh_views.bokeh_model),
]

article/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bokeh/', include('app_bokeh.urls')),
    url(r'^vtk/', include('app_vtk.urls')),
    url(r'^$', include('home.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from home import views as home_views

urlpatterns = [
    url(r'^',home_views.index ),
]

app_bokeh/models.py
#coding: utf-8
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
import os
import shutil


def create_bokeh_directory(id):
    if not os.path.exists(settings.BOKEH_DIR+"/{}/".format(id)):
        os.makedirs(settings.BOKEH_DIR+"/{}/".format(id))
    return settings.BOKEH_DIR_RELATIVE+"/{}/".format(id)

img_type_choices = (('line','line'),('circle','circle'), ('image','image'))

class BokehVisual(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    width = models.IntegerField(default=800)
    height = models.IntegerField(default=600)
    use_wgl = models.BooleanField(default=0)
    img_type = models.CharField(max_length=150, choices=img_type_choices)
    path     = models.TextField()

    def save(self, *args, **kwargs):
        res = super(BokehVisual, self).save(*args, **kwargs)
        kwargs['force_insert'] = False
        self.path = create_bokeh_directory(self.id)
        res = super(BokehVisual, self).save(*args, **kwargs)
        return res

    def default_save(self, *args, **kwargs):
        res = super(BokehVisual, self).save(*args, **kwargs)
        return res

    def __unicode__(self):
        return self.title

app_bokeh/forms.py
#coding: utf-8
from django import forms
import app_bokeh.models as models

class BokehVisualForm(forms.Form):
    title = forms.CharField(max_length=200, label=u"Title")
    description = forms.CharField(widget=forms.Textarea, label=u"Description")
    width = forms.IntegerField(label=u"Width")
    height = forms.IntegerField(label=u"Height")
    use_wgl = forms.BooleanField(label="Use wgl", required=False)
    img_type =  forms.ChoiceField(choices=models.img_type_choices, label=u"Image type")
    inputfile = forms.FileField(label=u"Visualization file")

app_bokeh/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
import os
import json
from django.contrib.auth.decorators import login_required
from annoying.decorators import render_to
from django.http import JsonResponse
from django.core import serializers
from django.http import HttpResponse

from .models import BokehVisual
from .forms import BokehVisualForm

from bokeh.plotting import figure, output_file, show
from bokeh.embed import components
from bokeh.models import AjaxDataSource, ColumnDataSource
import bokeh


def bokeh_json(request):
    visuals = {}
    if request.method == "GET":
        bokeh_id = request.GET.get('bokeh_id',None)
        if bokeh_id:
            models = BokehVisual.objects.get(pk=bokeh_id)
            visuals['get'] = json.loads(serializers.serialize('json', [models,]))
        else:
            models = BokehVisual.objects.all()
            visuals['get'] = json.loads(serializers.serialize('json', models))
    else:
        form = BokehVisualForm(request.POST, request.FILES)
        if form.is_valid():
            models = BokehVisual.objects.create()
            models.title = form.cleaned_data['title']
            models.description = form.cleaned_data['description']
            models.width = form.cleaned_data['width']
            models.height = form.cleaned_data['height']
            models.use_wgl = form.cleaned_data['use_wgl']
            models.img_type = form.cleaned_data['img_type']
            models.save()
            with open(os.path.join(models.path,'vis.dat'),'w') as f_out:
                f_out.write(form.cleaned_data['inputfile'].read())
            visuals['get'] = json.loads(serializers.serialize('json', [models,]))
        else:
            visuals['form_error'] = form.errors
    return JsonResponse(visuals)

def bokeh_image(request, bokeh_id):
    model = BokehVisual.objects.get(pk=bokeh_id)
    x_title = ""
    y_title = ""
    x = []
    y = []
    with open(os.path.join(model.path,'vis.dat'),'r') as f_in:
        titles = f_in.readline().split(',')
        x_title = titles[0].replace(' ','')
        y_title = titles[1].replace(' ','')
        for line in f_in:
            vals = line.split(',')
            x.append(float(vals[0]))
            y.append(float(vals[1]))

    source = ColumnDataSource(data={'x':x,'y':y})
    plot = figure(title= model.title,
                  x_axis_label= x_title,
                  y_axis_label= y_title,
                  plot_width = model.width,
                  plot_height = model.height)
    if model.use_wgl:
        plot = figure(title= model.title,
                      x_axis_label= x_title,
                      y_axis_label= y_title,
                      plot_width = model.width,
                      plot_height = model.height,
                      output_backend="webgl")
    else:
        plot = figure(title= model.title,
                      x_axis_label= x_title,
                      y_axis_label= y_title,
                      plot_width = model.width,
                      plot_height = model.height)

    if(model.img_type == 'line'):
        im = plot.line('x', 'y', source=source)
    if(model.img_type == 'circle'):
        im = plot.circle('x', 'y', source=source)

    callback = bokeh.models.CustomJS(args=dict(src=source,img=im, plt=plot), code="""
        var source = src;
        var image = img;
        var plot = plt;
        start_redrawing = Date.now();
        for (var i = 0; i < 100000; i++) {
            //plot.x_range.end += 0.0001;
            //image.change.emit();
            //plot.change.emit();
            source.change.emit();
        }
        stop_redrawing = Date.now();
        statistic_redrawing();
    """)
    button = bokeh.models.Button(label="Start redrawing", callback=callback)
    layout = bokeh.models.layouts.Column(button, plot)

    response_dict = {'script':'', 'div':''}
    response_dict['script'], response_dict['div'] = components(layout)
    return JsonResponse({'get':response_dict})


def data(request, bokeh_id):
    model = BokehVisual.objects.get(pk=bokeh_id)
    x = []
    y = []
    with open(os.path.join(model.path,'vis.dat'),'r') as f_in:
        titles = f_in.readline().split(',')
        for line in f_in:
            vals = line.split(',')
            x.append(float(vals[0]))
            y.append(float(vals[1]))
    return JsonResponse({'x':x,'y':y})


def bokeh_image_ajax_data(request, bokeh_id):
    model = BokehVisual.objects.get(pk=bokeh_id)
    x_title = ""
    y_title = ""
    with open(os.path.join(model.path,'vis.dat'),'r') as f_in:
        titles = f_in.readline().split(',')
        x_title = titles[0].replace(' ','')
        y_title = titles[1].replace(' ','')

    plot = figure(title= model.title,
                  x_axis_label= x_title,
                  y_axis_label= y_title,
                  plot_width = model.width,
                  plot_height = model.height)

    source = AjaxDataSource(data_url="http://localhost:8000/bokeh/id/{}/data/".format(bokeh_id), content_type="json", method="GET", mode='replace')
    source.data = dict(x=[], y=[])

    if(model.img_type == 'line'):
        im = plot.line('x', 'y', source=source)
    if(model.img_type == 'circle'):
        im = plot.circle('x', 'y', source=source)

    callback = bokeh.models.CustomJS(args=dict(src=source,plt=plot), code="""
        var source = src;
        var plot = plt;
        start_redrawing = Date.now();
        for (var i = 0; i < 100000; i++) {
            plot.change.emit();
        }
        stop_redrawing = Date.now();
        statistic_redrawing();
    """)
    button = bokeh.models.Button(label="Start redrawing", callback=callback)
    layout = bokeh.models.layouts.Column(button, plot)

    response_dict = {'script':'', 'div':''}
    response_dict['script'], response_dict['div'] = components(layout)
    return JsonResponse({'get':response_dict})



@render_to('bokeh_index.html')
def bokeh_index(request):
    return {"user":request.user, "current":"bokeh"}


@render_to('bokeh_visual.html')
def bokeh_model(request, bokeh_id):
    return {"user":request.user, "current":"bokeh", "bokeh_id":bokeh_id}


@render_to('bokeh_create.html')
def bokeh_form(request):
    form = BokehVisualForm()
    return {"user":request.user, 'form': form, "current":"bokeh"}

app_bokeh/templates/bokeh_create.html
{% extends "base_inner.html" %}
{% load widget_tweaks %}

{% block title %}Article - new bokeh{% endblock %}

{% block header %}Article-new bokeh{% endblock %}

{% block content %}
<div class="w3-bar">
    <h5><a href="/bokeh/" class="fa fa-step-backward w3-button"><b> Bokeh </b></a></h5>
    <h5><b><i class="fa fa-line-chart"></i> New bokeh</b></h5>

</div>

<div class="w3-container" id="error">

</div>

<div class="w3-container">
 <form class="w3-container" method="post" action="javascript:create_test();" id="form_1">
  {% csrf_token %}
    {% for field in form %}
          <p>
          <label>{{ field.label_tag }}</label>
          {{ field|add_class:"w3-input" }}
    {% endfor %}

   <p>
    <button class="w3-btn w3-input w3-blue-grey" onclick="submit">Create</button>
  </form>
</div>
<script type="text/javascript">

function create_test()
{
  $(document).ready(function(){
    var form_data;
    form_data = new FormData();

    form_data.append( 'csrfmiddlewaretoken', '{{ csrf_token }}' );
    form_data.append( 'inputfile', $('#id_inputfile').prop('files')[0] );
    form_data.append( 'title', $('#id_title').val() );
    form_data.append( 'description', $('#id_description').val() );
    form_data.append( 'width', $('#id_width').val() );
    form_data.append( 'height', $('#id_height').val() );
    form_data.append( 'use_wgl', document.getElementById('id_use_wgl').checked);
    form_data.append( 'img_type', $('#id_img_type').val())

    $.ajax({
      type: 'POST',
      url: '/bokeh/json/',
      data: form_data,
      contentType: false,
      processData: false,

      success: function(data){
        if (data.error)
        {
          $('#error').empty();
          $('#error').append('	<div class="w3-card-2 w3-container w3-row w3-white">\
        <h3> Error '+data.detail+'</h3>\
        </div>');
        }
        else if (data.form_error) {
          $('#error').empty();
          $('#error').append('	<div class="w3-card-2 w3-container w3-row w3-white">\
        <h3> Form error '+ JSON.stringify(data.form_error) +' </h3>\
        </div>');
        }
        else
        {
          window.location.href = '/bokeh/id/' + data.get[0].pk + '/';
        }
      }
    });
  });
}

</script>
{% endblock %}

app_bokeh/templates/bokeh_index.html
{% extends "base_inner.html" %}

{% block title %}Article-bokeh{% endblock %}

{% block header %}Article-bokeh{% endblock %}

{% block content %}

<div class="w3-bar">
  <div class="w3-bar-item"> <h5><b><i class="fa fa-line-chart"></i> Bokeh tests</b></h5> </div>
  <a href="/bokeh/form/" class="w3-bar-item w3-right w3-button">
		<h5><b><i class="fa fa-plus"></i> New</b></h5>
	</a>
</div>

<div class="w3-container" id="bokeh_vis">

</div>

<script type="text/javascript">

    $(document).ready(function(){
        $.ajax({
            url: "/bokeh/json/",
            dataType: "json",

            success: function(data){
            var trHTML="";

            if (data.error)
            {
             trHTML = '	<div class="w3-card-2 w3-container w3-row w3-white">\
            <h3> Error </h3>\
            </div>';

            }
            else if (data.get.length == 0)
            {
              trHTML = '	<div class="w3-card-2 w3-container w3-row w3-white">\
              <h3> No test exist </h3>\
              </div>';
            }
            else
            {
              $.each(data.get, function (i, bokeh_vis) {
                trHTML +=
                '<a href="/bokeh/id/'+bokeh_vis.pk+'">\
                 <div class="w3-card-2 w3-container w3-row w3-white w3-hover-gray">\
                       <div class="w3-col m2">\
                       </div>\
                       <div class="w3-col m10 w3-container">\
                         <h4>'+ bokeh_vis.fields.title + '</h4>\
                         <p><b>Description: </b>' + bokeh_vis.fields.description + '</p>\
                       </div>\
                 </div>\
                 </a>\
                 <p>'
              });
            }

          $('#bokeh_vis').append(trHTML);

            }});
          });
</script>

{% endblock %}

app_bokeh/templates/bokeh_visual.html
{% extends "base_inner.html" %}

{% block title %}Article-bokeh{% endblock %}

{% block header %}Article-bokeh{% endblock %}

{% block content %}

<div class="w3-bar">
  <h5><a href="/bokeh/" class="fa fa-step-backward w3-button"><b> Bokeh </b></a></h5>
	</a>
</div>

<div class="w3-container" id="bokeh_vis">

</div>

<script type="text/javascript">
var start_data;
var stop_data;
var start_redrawing;
var stop_redrawing;
var events_count=0;
function get_bokeh_image()
{
  $.ajax({
    url: "/bokeh/id/{{bokeh_id}}/image/",
    dataType: "json",
    success: function(data)
    {
      if(data.get)
      {
        $('#id_bokeh_img').append(data.get.div);
        $('#id_bokeh_script').append(data.get.script);
        stop_data = Date.now();
      }
    },
    complete: function (data) {
      statistic_load();
     }
  });
}
function statistic_load()
{
  $('#id_statistic_load').append('<p><span> Page load time: ' + String(stop_data - start_data) + ' ms<p><span>');
}
function statistic_redrawing()
{
  $('#id_statistic_redr').empty();
  $('#id_statistic_redr').append('<p><span> Redrawing 1000 times: ' + String(stop_redrawing - start_redrawing) + ' ms<p><span>');
}


$(document).ready(function(){
    $.ajax({
            url: "/bokeh/json/?bokeh_id={{bokeh_id}}",
            dataType: "json",

            success: function(data){
            var trHTML="";

            if (data.error)
            {
              trHTML = '	<div class="w3-card-2 w3-container w3-row w3-white">\
              <h3> Error </h3>\
              </div>';
              $('#bokeh_vis').append(trHTML);
            }
            else if (data.get.length == 0)
            {
              trHTML = '	<div class="w3-card-2 w3-container w3-row w3-white">\
              <h3> No test exist </h3>\
              </div>';
              $('#bokeh_vis').append(trHTML);
            }
            else
            {
              var bokeh_vis = data.get[0];
              trHTML +=
               '<div class="w3-card-2 w3-container w3-row w3-white">\
                     <div class="w3-col m2">\
                     </div>\
                     <div class="w3-col m10 w3-container">\
                       <h4>'+ bokeh_vis.fields.title + '</h4>\
                       <p><b>Description: </b>' + bokeh_vis.fields.description + '</p>\
                       <div id="id_bokeh_img"> </div>\
                       <div id="id_statistic_load"> </div>\
                       <div id="id_statistic_redr"> </div>\
                     </div>\
               </div>\
               <p>';
               $('#bokeh_vis').append(trHTML);
               start_data = Date.now();
               get_bokeh_image();
            }
        }
      });
    });
</script>
<div id="id_bokeh_script"> </div>
{% endblock %}